//----RECV

#define SCFExDB_GSRecv_RProtocol							0xF3
#define SCFExDB_GSRecv_EProtocol							0xE4
#define SCFExDB_GSRecv_CShopDataListRecv					0xA6
#define SCFExDB_GSRecv_CShopDataGiftRecv					0xF6
#define SCFExDB_GSRecv_CShopDataRecv						0xB9
#define SCFExDB_GSRecv_SetPlayerMasterSkill					0xDB
#define SCFExDB_GSRecv_GetAccountExtraInfo					0xCC
#define SCFExDB_GSRecv_GetPlayerExtraInfo					0xEE
#define SCFExDB_GSRecv_GetPlayerS5QuestInfo					0xDE
#define SCFExDB_GSRecv_GetOfficialHelperData				0xA1
#define SCFExDB_GSRecv_GetGuildGensInfo						0xC3
#define SCFExDB_GSRecv_GetWarehouseList_2					0xB4
#define SCFExDB_GSRecv_GetGuildWarehouseList				0xD6
#define SCFExDB_GSRecv_GetWarehouseNoItemEx_2				0xC6
#define SCFExDB_GSRecv_GetPetBot							0xE9
#define SCFExDB_GSRecv_CreateResultPetBot					0xAB
#define SCFExDB_GSRecv_GetWarehouseList_1					0xFB
#define SCFExDB_GSRecv_GetWarehouseListS6E2					0xBE
#define SCFExDB_GSRecv_GetWarehouseNoItemEx_1				0xAE
#define SCFExDB_GSRecv_GetCleanLuckyCoinsInfo				0xD1
#define SCFExDB_GSRecv_SiegeProtocol						0xE3
#define SCFExDB_GSRecv_GetBotReward							0xCB
#define SCFExDB_GSRecv_GetPlayerCustomQuestsInfo			0xA0
#define SCFExDB_GSRecv_GetTitanRankInfo						0xCD
#define SCFExDB_GSRecv_GetTitanLotteryInfo					0xCA

//----SEND

#define SCFExDB_GSSend_RProtocol							0xA0
#define SCFExDB_GSSend_EProtocol							0xC3
#define SCFExDB_GSSend_CShopDataListSave_Points				0xB3
#define SCFExDB_GSSend_CShopMuItemShopGetList				0xB4
#define SCFExDB_GSSend_CShopDataListSave_Normal				0xD6
#define SCFExDB_GSSend_CShopDataListSave_Gift				0xC6
#define SCFExDB_GSSend_CShopDataGiftSend					0xE8
#define SCFExDB_GSSend_CShopDataSend						0xAB
#define SCFExDB_GSSend_CShopAddGoblinCoin					0x9F
#define SCFExDB_GSSend_SetPlayerSkillTreeS6E2				0xFB
#define SCFExDB_GSSend_SetAccountExtraInfo					0xBE
#define SCFExDB_GSSend_SetPlayerExtraInfo					0xAE
#define SCFExDB_GSSend_SetPlayerMarryInfo					0xBD
#define SCFExDB_GSSend_SetStatusBan							0xF3
#define SCFExDB_GSSend_SetPlayerQuestSave					0xE3
#define SCFExDB_GSSend_DeletePlayerQ5Info					0xA6
#define SCFExDB_GSSend_GuildFamily							0xF6
#define SCFExDB_GSSend_GensLeaveFamily						0xB8
#define SCFExDB_GSSend_GetGuildWarehouseList				0xDB
#define SCFExDB_GSSend_SetGuildWarehouseList				0xCB
#define SCFExDB_GSSend_SetGuildWarehouseListS6E2			0xED
#define SCFExDB_GSSend_DelGuildWarehouseList				0xDE
#define SCFExDB_GSSend_AskPetBot							0xD5
#define SCFExDB_GSSend_SetPetBot							0xF1
#define SCFExDB_GSSend_CreatePetBot							0xF2
#define SCFExDB_GSSend_GetWarehouseListEx					0xA5
#define SCFExDB_GSSend_SetWarehouseListEx					0xC8
#define SCFExDB_GSSend_SetWarehouseListExS6E2				0xDA
#define SCFExDB_GSSend_SiegeProtocol						0xB5
#define SCFExDB_GSSend_GetAccounExtraInfo					0xC2
#define SCFExDB_GSSend_GetPlayerOfficialHelperInfo			0xF7
#define SCFExDB_GSSend_GetPlayerQ5Info						0xAA
#define SCFExDB_GSSend_RaceInsert							0xDF
#define SCFExDB_GSSend_RaceReward							0xE2
#define SCFExDB_GSSend_GetBotReward							0xC7
#define SCFExDB_GSSend_DelBotReward							0xCA
#define SCFExDB_GSSend_GetPlayerCustomQuestsInfo			0xAF
#define SCFExDB_GSSend_SendPlayerCustomQuestsInfo			0xB9
#define SCFExDB_GSSend_SetOfficialHelperData				0xE7
#define SCFExDB_GSSend_GetMasterSkillTreeData				0xFA
#define SCFExDB_GSSend_SetWarehouseMoneyEx					0xB7
#define SCFExDB_GSSend_SetResetLog							0xCE
#define SCFExDB_GSSend_SetTitanRankInfo						0xCD
#define SCFExDB_GSSend_SendTitanLotteryInfo					0xCC
#define SCFExDB_GSSend_DuelScore							0xC9
#define SCFExDB_GSSend_DGScore								0xB1
#define SCFExDB_GSSend_DGScore								0xB1
#define SCFExDB_GSSend_IGScore								0xB6
#define SCFExDB_GSSend_MonsterKilled						0xBA
#define SCFExDB_GSSend_RewardInfo							0xEE